version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["sh","./start.sh"]
    volumes:
      - .:/todoapp
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=linkan
      - POSTGRES_PASSWORD=password
volumes:
  postgres_data:



